//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("GeeSuthSoft.KSA.ZATCA")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("7.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("7.0")]
[assembly: System.Reflection.AssemblyProductAttribute("GeeSuthSoft.KSA.ZATCA")]
[assembly: System.Reflection.AssemblyTitleAttribute("GeeSuthSoft.KSA.ZATCA")]
[assembly: System.Reflection.AssemblyVersionAttribute("7.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/GeeSuth/GeeSuthSoft.KSA.ZATCA")]

// Generated by the MSBuild WriteCodeFragment class.

