//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeeSuthSoft.KSA.ZATCA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeeSuthSoft.KSA.ZATCA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;cac:AdditionalDocumentReference&gt;
        ///        &lt;cbc:ID&gt;QR&lt;/cbc:ID&gt;
        ///        &lt;cac:Attachment&gt;
        ///            &lt;cbc:EmbeddedDocumentBinaryObject mimeCode=&quot;text/plain&quot;&gt;TLV_QRCODE_STRING&lt;/cbc:EmbeddedDocumentBinaryObject&gt;
        ///        &lt;/cac:Attachment&gt;
        ///&lt;/cac:AdditionalDocumentReference&gt;.
        /// </summary>
        internal static string ZatcaDataQr {
            get {
                return ResourceManager.GetString("ZatcaDataQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;cac:Signature&gt;
        ///      &lt;cbc:ID&gt;urn:oasis:names:specification:ubl:signature:Invoice&lt;/cbc:ID&gt;
        ///      &lt;cbc:SignatureMethod&gt;urn:oasis:names:specification:ubl:dsig:enveloped:xades&lt;/cbc:SignatureMethod&gt;
        ///&lt;/cac:Signature&gt;.
        /// </summary>
        internal static string ZatcaDataSignature {
            get {
                return ResourceManager.GetString("ZatcaDataSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ext:UBLExtensions&gt;
        ///    &lt;ext:UBLExtension&gt;
        ///        &lt;ext:ExtensionURI&gt;urn:oasis:names:specification:ubl:dsig:enveloped:xades&lt;/ext:ExtensionURI&gt;
        ///        &lt;ext:ExtensionContent&gt;
        ///            &lt;sig:UBLDocumentSignatures xmlns:sig=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2&quot; xmlns:sac=&quot;urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2&quot; xmlns:sbc=&quot;urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2&quot;&gt;
        ///                &lt;sac:SignatureInform [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZatcaDataUbl {
            get {
                return ResourceManager.GetString("ZatcaDataUbl", resourceCulture);
            }
        }
    }
}
